name 'mumble'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures a Mumble server.'
long_description 'Application cookbook which installs and configures a Mumble server.'
version '1.0.1'

supports 'ubuntu', '>= 14.04'
supports 'centos', '>= 7.1'

depends 'apt'
depends 'libartifact', '~> 1.3'
depends 'rc', '~> 1.5'
depends 'poise-service'
depends 'ubuntu'
depends 'yum'
depends 'yum-epel'
depends 'yum-centos'
